title: Vladyslav Siriniok
email: siriniok@gmail.com
description: >
  Notes on drinking code.
baseurl: ""
url: "https://siriniok.me"
twitter_username: siriniok
github_username:  siriniok

# Build settings
markdown: kramdown
exclude:
  - docs

plugins:
  - octopress-debugger
  - jekyll-redirect-from
