---
title: Vladyslav Siriniok
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Vladyslav Siriniok
email: vlad@siriniok.me
twitter:
  username: siriniok
  card: summary
social:
  name: Vladyslav Siriniok
  links:
  - https://twitter.com/siriniok
  - https://facebook.com/siriniok
  - https://ua.linkedin.com/in/siriniok
  - https://github.com/siriniok
description: 'A blog on tech and science by Vladyslav Siriniok

'
url: https://siriniok.me
permalink: pretty
twitter_username: siriniok
github_username: siriniok
markdown: kramdown
exclude:
- docs
plugins:
- octopress-debugger
- jekyll-redirect-from
- jekyll-twitter-plugin
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
