title: A Bottle of Code
email: siriniok@gmail.com
description: >
  Notes on drinking code.
url: "http://siriniok.com"
permalink: pretty
twitter_username: siriniok
github_username:  siriniok

# Build settings
markdown: kramdown
exclude:
  - docs

plugins:
  - octopress-debugger
  - jekyll-redirect-from
  - jekyll-twitter-plugin
  - jekyll-gist
