title: Vladyslav Siriniok
email: siriniok@gmail.com
description: >
  mnmlist, developer, writer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://siriniok.github.io" # the base hostname & protocol for your site
twitter_username: siriniok
github_username:  siriniok

# Build settings
markdown: kramdown
