title: Vladyslav Siriniok
email: siriniok@gmail.com
description: >
  A blog on tech and science by Vladyslav Siriniok
url: "http://siriniok.com"
permalink: pretty
twitter_username: siriniok
github_username:  siriniok

# Build settings
markdown: kramdown
exclude:
  - docs

plugins:
  - octopress-debugger
  - jekyll-redirect-from
  - jekyll-twitter-plugin
  - jekyll-gist
