---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
  description: title
  config:
    required: true
- type: datetime
  name: date
  label: date
  description: date
  config:
    display_utc: false
    date_format: YYYY-MM-DD
    time_format: HH:MM ZZ
    required: true
- type: text
  name: categories
  label: 'categories '
  config:
    required: true
  default: notes
- type: text
  name: layout
  label: layout
  description: layout
  default: post
  config:
    required: true
- type: text
  name: author
  label: author
  description: author
  config:
    required: true
  default: Vladyslav Siriniok
- name: image
  type: file
  config:
    maxSize: 250
  label: image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
pages:
- _posts/shitty-mvp.md
- _posts/what-really-guides-me-part-i.md
